In [2]:
import nltk

In [3]:
nltk.download("all", quiet=True)

True

In [4]:
from nltk.tokenize import word_tokenize
text = "Friends, Romans, Countrymen, lend me your ears;."
text = '그대의 보름달이 뜨는날 날 사랑해줘요'
print(word_tokenize(text))

['그대의', '보름달이', '뜨는날', '날', '사랑해줘요']


In [5]:
from nltk.tokenize import sent_tokenize
text = "내겐 뭐 원하녜 다른 건 안바래 이것만 원하네, 그대 손잡고 안 놔줄래 보라빛 밤, i like it like it \
    오 그대여 만나서 또 이 밤을 기다릴게요. 나나나나 나나나나 보라빛 밤 술은 입에도 안댔는데, 나 조금 어지러운 것 같애. \
    지금 맘이 참 답답한데, 날 안고써 입 맞출래, 더 같이 있자. 아직 이르잖아."

print(sent_tokenize(text))

['내겐 뭐 원하녜 다른 건 안바래 이것만 원하네, 그대 손잡고 안 놔줄래 보라빛 밤, i like it like it     오 그대여 만나서 또 이 밤을 기다릴게요.', '나나나나 나나나나 보라빛 밤 술은 입에도 안댔는데, 나 조금 어지러운 것 같애.', '지금 맘이 참 답답한데, 날 안고써 입 맞출래, 더 같이 있자.', '아직 이르잖아.']


In [6]:
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [7]:
# 원핫 인코딩을 적용할 예제 데이터를 설정합니다
data = ['cold', 'cold', 'warm', 'cold', 'hot', 'hot', 'warm', 'cold', 'warm', 'hot']
print(set(data))
values = array(data)
print(values)

{'cold', 'warm', 'hot'}
['cold' 'cold' 'warm' 'cold' 'hot' 'hot' 'warm' 'cold' 'warm' 'hot']


In [8]:
# Integer Encoding을 진행합니다.
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

[0 0 2 0 1 1 2 0 2 1]


In [9]:
# One-hot Encoding을 진행합니다.
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
print(integer_encoded.reshape(len(integer_encoded), 1))
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[0]
 [0]
 [2]
 [0]
 [1]
 [1]
 [2]
 [0]
 [2]
 [1]]
[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [10]:
# One-hot Encoding을 적용한 예제를 다시 string 형태로 변경합니다.
inverted = label_encoder.inverse_transform([argmax(onehot_encoded[0, :])])
print(inverted)

['cold']
